server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartrecruit_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  info:
    title: SmartRecruit API
    description: "API Document for project"
    version: ${project.version}
  show-actuator: true

jwt:
  secret-key: hJ1sWDI69pxl2VThpiEaBAj5eYSVwey6
  expiration: 86400000


