server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration
  
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  info:
    title: SmartRecruit API
    description: "API Document for project"
    version: ${project.version}
  show-actuator: true

firebase:
  service-account-path: "classpath:firebase-service-account.json"

admin:
  creation:
    enabled: true
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    full-name: ${ADMIN_FULLNAME}
    username: "admin"