package com.ptit.thesis.smartrecruit.enums;

/**
 * Enum này chứa danh sách các quốc gia trên thế giới.
 * Mỗi quốc gia bao gồm tên tiếng Việt và mã quốc gia theo chuẩn ISO 3166-1 alpha-2.
 * Hữu ích cho việc chọn quốc tịch trong các biểu mẫu, ví dụ như trên trang web tuyển dụng.
 */
public enum Nationality {
    AFGHANISTAN("Afghanistan", "AF"),
    ALBANIA("Albania", "AL"),
    ALGERIA("Algeria", "DZ"),
    AMERICAN_SAMOA("Samoa thuộc Mỹ", "AS"),
    ANDORRA("Andorra", "AD"),
    ANGOLA("Angola", "AO"),
    ANGUILLA("Anguilla", "AI"),
    ANTARCTICA("Nam Cực", "AQ"),
    ANTIGUA_AND_BARBUDA("Antigua và Barbuda", "AG"),
    ARGENTINA("Argentina", "AR"),
    ARMENIA("Armenia", "AM"),
    ARUBA("Aruba", "AW"),
    AUSTRALIA("Úc", "AU"),
    AUSTRIA("Áo", "AT"),
    AZERBAIJAN("Azerbaijan", "AZ"),
    BAHAMAS("Bahamas", "BS"),
    BAHRAIN("Bahrain", "BH"),
    BANGLADESH("Bangladesh", "BD"),
    BARBADOS("Barbados", "BB"),
    BELARUS("Belarus", "BY"),
    BELGIUM("Bỉ", "BE"),
    BELIZE("Belize", "BZ"),
    BENIN("Benin", "BJ"),
    BERMUDA("Bermuda", "BM"),
    BHUTAN("Bhutan", "BT"),
    BOLIVIA("Bolivia", "BO"),
    BOSNIA_AND_HERZEGOVINA("Bosnia và Herzegovina", "BA"),
    BOTSWANA("Botswana", "BW"),
    BRAZIL("Brazil", "BR"),
    BRITISH_INDIAN_OCEAN_TERRITORY("Lãnh thổ Ấn Độ Dương thuộc Anh", "IO"),
    BRUNEI_DARUSSALAM("Brunei", "BN"),
    BULGARIA("Bulgaria", "BG"),
    BURKINA_FASO("Burkina Faso", "BF"),
    BURUNDI("Burundi", "BI"),
    CAMBODIA("Campuchia", "KH"),
    CAMEROON("Cameroon", "CM"),
    CANADA("Canada", "CA"),
    CAPE_VERDE("Cape Verde", "CV"),
    CAYMAN_ISLANDS("Quần đảo Cayman", "KY"),
    CENTRAL_AFRICAN_REPUBLIC("Cộng hòa Trung Phi", "CF"),
    CHAD("Chad", "TD"),
    CHILE("Chile", "CL"),
    CHINA("Trung Quốc", "CN"),
    CHRISTMAS_ISLAND("Đảo Giáng Sinh", "CX"),
    COCOS_KEELING_ISLANDS("Quần đảo Cocos (Keeling)", "CC"),
    COLOMBIA("Colombia", "CO"),
    COMOROS("Comoros", "KM"),
    CONGO("Congo", "CG"),
    CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE("Cộng hòa Dân chủ Congo", "CD"),
    COOK_ISLANDS("Quần đảo Cook", "CK"),
    COSTA_RICA("Costa Rica", "CR"),
    COTE_DIVOIRE("Bờ Biển Ngà", "CI"),
    CROATIA("Croatia", "HR"),
    CUBA("Cuba", "CU"),
    CYPRUS("Síp", "CY"),
    CZECH_REPUBLIC("Cộng hòa Séc", "CZ"),
    DENMARK("Đan Mạch", "DK"),
    DJIBOUTI("Djibouti", "DJ"),
    DOMINICA("Dominica", "DM"),
    DOMINICAN_REPUBLIC("Cộng hòa Dominica", "DO"),
    ECUADOR("Ecuador", "EC"),
    EGYPT("Ai Cập", "EG"),
    EL_SALVADOR("El Salvador", "SV"),
    EQUATORIAL_GUINEA("Guinea Xích Đạo", "GQ"),
    ERITREA("Eritrea", "ER"),
    ESTONIA("Estonia", "EE"),
    ETHIOPIA("Ethiopia", "ET"),
    FALKLAND_ISLANDS_MALVINAS("Quần đảo Falkland (Malvinas)", "FK"),
    FAROE_ISLANDS("Quần đảo Faroe", "FO"),
    FIJI("Fiji", "FJ"),
    FINLAND("Phần Lan", "FI"),
    FRANCE("Pháp", "FR"),
    FRENCH_GUIANA("Guiana thuộc Pháp", "GF"),
    FRENCH_POLYNESIA("Polynesia thuộc Pháp", "PF"),
    GABON("Gabon", "GA"),
    GAMBIA("Gambia", "GM"),
    GEORGIA("Georgia", "GE"),
    GERMANY("Đức", "DE"),
    GHANA("Ghana", "GH"),
    GIBRALTAR("Gibraltar", "GI"),
    GREECE("Hy Lạp", "GR"),
    GREENLAND("Greenland", "GL"),
    GRENADA("Grenada", "GD"),
    GUADELOUPE("Guadeloupe", "GP"),
    GUAM("Guam", "GU"),
    GUATEMALA("Guatemala", "GT"),
    GUINEA("Guinea", "GN"),
    GUINEA_BISSAU("Guinea-Bissau", "GW"),
    GUYANA("Guyana", "GY"),
    HAITI("Haiti", "HT"),
    HONDURAS("Honduras", "HN"),
    HONG_KONG("Hồng Kông", "HK"),
    HUNGARY("Hungary", "HU"),
    ICELAND("Iceland", "IS"),
    INDIA("Ấn Độ", "IN"),
    INDONESIA("Indonesia", "ID"),
    IRAN_ISLAMIC_REPUBLIC_OF("Iran", "IR"),
    IRAQ("Iraq", "IQ"),
    IRELAND("Ireland", "IE"),
    ISRAEL("Israel", "IL"),
    ITALY("Ý", "IT"),
    JAMAICA("Jamaica", "JM"),
    JAPAN("Nhật Bản", "JP"),
    JORDAN("Jordan", "JO"),
    KAZAKHSTAN("Kazakhstan", "KZ"),
    KENYA("Kenya", "KE"),
    KIRIBATI("Kiribati", "KI"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF("Triều Tiên", "KP"),
    KOREA_REPUBLIC_OF("Hàn Quốc", "KR"),
    KUWAIT("Kuwait", "KW"),
    KYRGYZSTAN("Kyrgyzstan", "KG"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("Lào", "LA"),
    LATVIA("Latvia", "LV"),
    LEBANON("Lebanon", "LB"),
    LESOTHO("Lesotho", "LS"),
    LIBERIA("Liberia", "LR"),
    LIBYAN_ARAB_JAMAHIRIYA("Libya", "LY"),
    LIECHTENSTEIN("Liechtenstein", "LI"),
    LITHUANIA("Litva", "LT"),
    LUXEMBOURG("Luxembourg", "LU"),
    MACAO("Ma Cao", "MO"),
    MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF("Bắc Macedonia", "MK"),
    MADAGASCAR("Madagascar", "MG"),
    MALAWI("Malawi", "MW"),
    MALAYSIA("Malaysia", "MY"),
    MALDIVES("Maldives", "MV"),
    MALI("Mali", "ML"),
    MALTA("Malta", "MT"),
    MARSHALL_ISLANDS("Quần đảo Marshall", "MH"),
    MARTINIQUE("Martinique", "MQ"),
    MAURITANIA("Mauritania", "MR"),
    MAURITIUS("Mauritius", "MU"),
    MEXICO("Mexico", "MX"),
    MICRONESIA_FEDERATED_STATES_OF("Micronesia", "FM"),
    MOLDOVA_REPUBLIC_OF("Moldova", "MD"),
    MONACO("Monaco", "MC"),
    MONGOLIA("Mông Cổ", "MN"),
    MONTENEGRO("Montenegro", "ME"),
    MONTSERRAT("Montserrat", "MS"),
    MOROCCO("Maroc", "MA"),
    MOZAMBIQUE("Mozambique", "MZ"),
    MYANMAR("Myanmar", "MM"),
    NAMIBIA("Namibia", "NA"),
    NAURU("Nauru", "NR"),
    NEPAL("Nepal", "NP"),
    NETHERLANDS("Hà Lan", "NL"),
    NEW_CALEDONIA("New Caledonia", "NC"),
    NEW_ZEALAND("New Zealand", "NZ"),
    NICARAGUA("Nicaragua", "NI"),
    NIGER("Niger", "NE"),
    NIGERIA("Nigeria", "NG"),
    NIUE("Niue", "NU"),
    NORFOLK_ISLAND("Đảo Norfolk", "NF"),
    NORTHERN_MARIANA_ISLANDS("Quần đảo Bắc Mariana", "MP"),
    NORWAY("Na Uy", "NO"),
    OMAN("Oman", "OM"),
    PAKISTAN("Pakistan", "PK"),
    PALAU("Palau", "PW"),
    PALESTINIAN_TERRITORY_OCCUPIED("Lãnh thổ Palestine", "PS"),
    PANAMA("Panama", "PA"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG"),
    PARAGUAY("Paraguay", "PY"),
    PERU("Peru", "PE"),
    PHILIPPINES("Philippines", "PH"),
    PITCAIRN("Quần đảo Pitcairn", "PN"),
    POLAND("Ba Lan", "PL"),
    PORTUGAL("Bồ Đào Nha", "PT"),
    PUERTO_RICO("Puerto Rico", "PR"),
    QATAR("Qatar", "QA"),
    REUNION("Réunion", "RE"),
    ROMANIA("Romania", "RO"),
    RUSSIAN_FEDERATION("Nga", "RU"),
    RWANDA("Rwanda", "RW"),
    SAINT_HELENA("Saint Helena", "SH"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts và Nevis", "KN"),
    SAINT_LUCIA("Saint Lucia", "LC"),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre và Miquelon", "PM"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent và Grenadines", "VC"),
    SAMOA("Samoa", "WS"),
    SAN_MARINO("San Marino", "SM"),
    SAO_TOME_AND_PRINCIPE("São Tomé và Príncipe", "ST"),
    SAUDI_ARABIA("Ả Rập Xê Út", "SA"),
    SENEGAL("Senegal", "SN"),
    SERBIA("Serbia", "RS"),
    SEYCHELLES("Seychelles", "SC"),
    SIERRA_LEONE("Sierra Leone", "SL"),
    SINGAPORE("Singapore", "SG"),
    SLOVAKIA("Slovakia", "SK"),
    SLOVENIA("Slovenia", "SI"),
    SOLOMON_ISLANDS("Quần đảo Solomon", "SB"),
    SOMALIA("Somalia", "SO"),
    SOUTH_AFRICA("Nam Phi", "ZA"),
    SPAIN("Tây Ban Nha", "ES"),
    SRI_LANKA("Sri Lanka", "LK"),
    SUDAN("Sudan", "SD"),
    SURINAME("Suriname", "SR"),
    SVALBARD_AND_JAN_MAYEN("Svalbard và Jan Mayen", "SJ"),
    SWAZILAND("Eswatini", "SZ"),
    SWEDEN("Thụy Điển", "SE"),
    SWITZERLAND("Thụy Sĩ", "CH"),
    SYRIAN_ARAB_REPUBLIC("Syria", "SY"),
    TAIWAN_PROVINCE_OF_CHINA("Đài Loan", "TW"),
    TAJIKISTAN("Tajikistan", "TJ"),
    TANZANIA_UNITED_REPUBLIC_OF("Tanzania", "TZ"),
    THAILAND("Thái Lan", "TH"),
    TIMOR_LESTE("Đông Timor", "TL"),
    TOGO("Togo", "TG"),
    TOKELAU("Tokelau", "TK"),
    TONGA("Tonga", "TO"),
    TRINIDAD_AND_TOBAGO("Trinidad và Tobago", "TT"),
    TUNISIA("Tunisia", "TN"),
    TURKEY("Thổ Nhĩ Kỳ", "TR"),
    TURKMENISTAN("Turkmenistan", "TM"),
    TURKS_AND_CAICOS_ISLANDS("Quần đảo Turks và Caicos", "TC"),
    TUVALU("Tuvalu", "TV"),
    UGANDA("Uganda", "UG"),
    UKRAINE("Ukraina", "UA"),
    UNITED_ARAB_EMIRATES("Các Tiểu vương quốc Ả Rập Thống nhất", "AE"),
    UNITED_KINGDOM("Vương quốc Anh", "GB"),
    UNITED_STATES("Hoa Kỳ", "US"),
    URUGUAY("Uruguay", "UY"),
    UZBEKISTAN("Uzbekistan", "UZ"),
    VANUATU("Vanuatu", "VU"),
    VATICAN_CITY_STATE("Thành Vatican", "VA"),
    VENEZUELA("Venezuela", "VE"),
    VIETNAM("Việt Nam", "VN"),
    VIRGIN_ISLANDS_BRITISH("Quần đảo Virgin thuộc Anh", "VG"),
    VIRGIN_ISLANDS_US("Quần đảo Virgin thuộc Mỹ", "VI"),
    WALLIS_AND_FUTUNA("Wallis và Futuna", "WF"),
    WESTERN_SAHARA("Tây Sahara", "EH"),
    YEMEN("Yemen", "YE"),
    ZAMBIA("Zambia", "ZM"),
    ZIMBABWE("Zimbabwe", "ZW");

    private final String vietnameseName;
    private final String code;

    Nationality(String vietnameseName, String code) {
        this.vietnameseName = vietnameseName;
        this.code = code;
    }

    /**
     * Trả về tên tiếng Việt của quốc gia.
     * @return Tên tiếng Việt (String)
     */
    public String getVietnameseName() {
        return vietnameseName;
    }

    /**
     * Trả về mã quốc gia theo chuẩn ISO 3166-1 alpha-2.
     * @return Mã quốc gia (String)
     */
    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return this.vietnameseName;
    }
}
